### PR TITLE
perf: reclaim ~10.7 KB RAM — BLE GATT ceiling + config de-double-buffering

### PR DESCRIPTION
**Pull request by davelee98**
Reclaims **~10.7 KB of RAM on ESP32** and **~8.5 KB on nRF52840** by removing over-declared BLE buffers and redundant copies of the 4 KB config blob. No protocol change, no on-flash format change, no client-visible behavior change.

All figures below are measured by diffing linker output and ELF symbol tables between the pre- and post-change trees, not estimated.

### 1. `chore(protocol)`: sync vendored header
Pulls the canonical `opendisplay_protocol.h` (LAN section + `OD_BLE_MAX_FRAME`) via `tools/sync_protocol_header.py --push`. No firmware behavior; it supplies the constant the next commit uses.

### 2. `perf(ble)`: declare a 256-byte GATT ceiling, shrink the response ring

The BLE surface advertised more than the wire could carry, and the declarations disagreed. `setMTU(512)` negotiated a 512-byte ATT MTU and `createCharacteristic()` passed no `max_len` (inheriting NimBLE's 512 default), while the app silently discarded any write over `MAX_COMMAND_SIZE` (256) with no ATT error to the peer — on a Write-NR pipe frame that surfaced only as a stalled window.

Nothing needed the headroom: `PIPE_MAX_FRAME` is 244, the largest legitimate inbound frame is a 233-byte encrypted config chunk, and nRF is hard-capped by the SoftDevice at ATT MTU 247.

- Oversize writes now get a proper ATT `0x0D` rejection instead of vanishing.
- On nRF, `max_len` is reserved for real by the SoftDevice (`vloc = BLE_GATTS_VLOC_STACK`), so 512 cost 512 B of attribute table with half unreachable behind the 247 cap.
- `responseQueue`: **5120 → 2600 B** (~2.5 KB DRAM).

Also collapses an ODR violation: `MAX_RESPONSE_SIZE` / `RESPONSE_QUEUE_SIZE` / `ResponseQueueItem` were defined in `main.h` *and* redeclared in `communication.cpp` with a hardcoded 512, so the bound checked before the `memcpy` lived in a different file from the slot it guarded.

### 3. `perf(config)`: stop triple-buffering the 4 KB config blob

Config held four independent ~4 KB buffers in `.bss` plus a fifth on the stack — 16,436 B held permanently (6.9% of usable RAM on nRF52840) for a path used a few times per boot:

| Buffer | Size | Storage |
|---|---|---|
| `chunkedWriteState` | 4116 | `.bss` |
| `saveConfig::config` | 4112 | `.bss` (static) |
| `loadConfig::config` | 4112 | `.bss` (static) |
| `loadGlobalConfig::configData` | 4096 | `.bss` (static) |
| `handleReadConfig::configData` | 4096 | **stack** |

The waste was double-buffering on every path. `config_storage_t` bundled a `uint8_t[MAX_CONFIG_SIZE]` behind its 16-byte header, so `saveConfig()`/`loadConfig()` each kept a private 4 KB staging copy purely to have somewhere contiguous to work from, then `memcpy`'d to/from the caller — whose buffer was itself another 4 KB static.

- Split `config_storage_t` into a 16-byte `config_header_t`; the payload streams straight to/from the caller's buffer. **The on-flash byte layout is unchanged** (header followed by `data_len` bytes), pinned by a `static_assert` — padding there would shift the payload offset and orphan every stored config.
- `loadConfig()`'s capacity check moved **before** the payload read rather than after staging: the read target is now the caller's buffer, so that bound is what prevents an overrun.
- The three consumers needing a whole blob in RAM now share one `configScratch[MAX_CONFIG_SIZE]`. Safe because all config paths run synchronously on the loop task and none nest. This also removes the 4 KB stack array in `handleReadConfig` — an overflow risk on the loop task independent of the `.bss` win. `chunkedWriteState` deliberately does **not** share it, since it stays live across BLE commands.
- Factory provisioning passes a flash pointer, so that path also loses a 4 KB flash→RAM copy at first boot.
- Collapses the same ODR footgun as above: `chunked_write_state_t` was defined in `main.h` *and* redefined in `communication.cpp` with a hardcoded `4096` in place of `MAX_CONFIG_SIZE`, with the guard in `handleWriteConfigChunk()` sized in a different file from the slot it protects. Since this PR resizes config buffers, that drift could have turned a shrink into an overrun.

## Measured result

| Target | Before | After | Δ |
|---|---|---|---|
| nrf52840custom | 51,316 | 43,084 | **−8232** |
| esp32-c3-N16 | 104,212 | 95,980 | **−8232** |
| esp32-s3-N16R8 | 114,820 | 106,596 | **−8232** |

(Config commit alone; the BLE commit adds ~2.5 KB more on ESP32 and 256 B on nRF.) The three staging symbols are gone from both ELFs, replaced by one 4096 B `configScratch`.

## Testing

Builds green on all three CI environments (`nrf52840custom`, `esp32-s3-N16R8`, `esp32-c3-N16`) as of the branch point.

**Not verified on hardware** — please exercise before merging:
- Config write + read-back round-trip (this PR rewrote the config file I/O).
- Reading a config written by older firmware. The format is unchanged so this should be a no-op, but it is the assumption the change rests on.
- The ATT `0x0D` oversize-write rejection path, and a real image push over BLE.

## Note on CI: pre-existing break on `main`

`main` currently **fails to build both ESP32 environments**, independent of this PR:

```
src/encryption.cpp:190:5: error: 'ccm_session_free' was not declared in this scope
```

`ccm_session_free` is defined at `encryption.cpp:252` but called at line 190, with no forward declaration — introduced by #118. I verified this by building `upstream/main` alone at `3af8d68`. This branch merges cleanly into `main` (no conflicts) and builds `nrf52840custom` green on the merge result, but the ESP32 jobs will be red until that ordering bug is fixed. Happy to send a separate one-line PR for it if useful.

### CODE REVIEW

**Comment by jonasniesner** [comment]
@davelee98 can you have a look at the merge conflicts and resolve them?

File: src/ble_init.cpp [hunk 1]
```diff
@@ -253,8 +253,9 @@ void ble_init_esp32(bool update_manufacturer_data) {
     String deviceName = "OD" + getChipIdHex();
     writeSerial("Device name will be: " + deviceName);
     BLEDevice::init(deviceName.c_str());
-    writeSerial("Setting BLE MTU to 512...");
-    BLEDevice::setMTU(512);
+    // Preferred only: the central drives the exchange and may settle lower.
+    writeSerial("Setting preferred BLE ATT MTU to " + String(OD_BLE_PREFERRED_ATT_MTU) + "...");
```
Comment (cryptomilk) [inline src/ble_init.cpp]: Should be od_log_info()

**Review by cryptomilk — CHANGES_REQUESTED** [review]
